# Generated by Django 4.0.5 on 2022-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depart_desp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='depart_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
