# Generated by Django 4.0.5 on 2022-06-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_department_depart_desp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depart_desp',
            new_name='depart_desps',
        ),
    ]
