# Generated by Django 4.0.5 on 2022-06-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
